CREATE TABLE "ai-madlib-generator-v2_accounts" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "ai-madlib-generator-v2_accounts_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "ai-madlib-generator-v2_adlib_categories" (
	"adlibId" integer NOT NULL,
	"categoryId" integer NOT NULL,
	CONSTRAINT "ai-madlib-generator-v2_adlib_categories_adlibId_categoryId_pk" PRIMARY KEY("adlibId","categoryId")
);
--> statement-breakpoint
CREATE TABLE "ai-madlib-generator-v2_adlib_results" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai-madlib-generator-v2_adlib_results_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"adlibId" integer NOT NULL,
	"resultText" text NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai-madlib-generator-v2_adlibs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai-madlib-generator-v2_adlibs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"prompt" varchar(255) NOT NULL,
	"text" text NOT NULL,
	"isHidden" boolean DEFAULT false NOT NULL,
	"isPg" boolean DEFAULT false NOT NULL,
	"temperature" real DEFAULT 0.7 NOT NULL,
	"topP" real DEFAULT 1 NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai-madlib-generator-v2_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai-madlib-generator-v2_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai-madlib-generator-v2_sessions" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai-madlib-generator-v2_users" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "ai-madlib-generator-v2_verification_tokens" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "ai-madlib-generator-v2_verification_tokens_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_accounts" ADD CONSTRAINT "ai-madlib-generator-v2_accounts_userId_ai-madlib-generator-v2_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."ai-madlib-generator-v2_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_adlib_categories" ADD CONSTRAINT "ai-madlib-generator-v2_adlib_categories_adlibId_ai-madlib-generator-v2_adlibs_id_fk" FOREIGN KEY ("adlibId") REFERENCES "public"."ai-madlib-generator-v2_adlibs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_adlib_categories" ADD CONSTRAINT "ai-madlib-generator-v2_adlib_categories_categoryId_ai-madlib-generator-v2_categories_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."ai-madlib-generator-v2_categories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_adlib_results" ADD CONSTRAINT "ai-madlib-generator-v2_adlib_results_adlibId_ai-madlib-generator-v2_adlibs_id_fk" FOREIGN KEY ("adlibId") REFERENCES "public"."ai-madlib-generator-v2_adlibs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_adlib_results" ADD CONSTRAINT "ai-madlib-generator-v2_adlib_results_createdById_ai-madlib-generator-v2_users_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."ai-madlib-generator-v2_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_adlibs" ADD CONSTRAINT "ai-madlib-generator-v2_adlibs_createdById_ai-madlib-generator-v2_users_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."ai-madlib-generator-v2_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_sessions" ADD CONSTRAINT "ai-madlib-generator-v2_sessions_userId_ai-madlib-generator-v2_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."ai-madlib-generator-v2_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "ai-madlib-generator-v2_accounts" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "categories_name_idx" ON "ai-madlib-generator-v2_categories" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "ai-madlib-generator-v2_sessions" USING btree ("userId");