CREATE TABLE "ai-madlib-generator-v2_feature_toggles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai-madlib-generator-v2_feature_toggles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"isEnabled" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
