CREATE TABLE "ai-madlib-generator-v2_adlib_tones" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai-madlib-generator-v2_adlib_tones_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"style" varchar(255) NOT NULL,
	"prompt" text NOT NULL,
	"character" varchar(255) NOT NULL,
	"toneLevel" integer NOT NULL,
	"available" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_adlibs" ADD COLUMN "isFeatured" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_adlibs" ADD COLUMN "toneId" integer;--> statement-breakpoint
CREATE UNIQUE INDEX "adlib_tones_tone_level_idx" ON "ai-madlib-generator-v2_adlib_tones" USING btree ("toneLevel");--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_adlibs" ADD CONSTRAINT "ai-madlib-generator-v2_adlibs_toneId_ai-madlib-generator-v2_adlib_tones_id_fk" FOREIGN KEY ("toneId") REFERENCES "public"."ai-madlib-generator-v2_adlib_tones"("id") ON DELETE set null ON UPDATE no action;