CREATE TABLE "ai-madlib-generator-v2_adlib_comments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai-madlib-generator-v2_adlib_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"adlibId" integer NOT NULL,
	"authorName" varchar(50),
	"body" text NOT NULL,
	"isHidden" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai-madlib-generator-v2_adlib_reactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai-madlib-generator-v2_adlib_reactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"adlibId" integer NOT NULL,
	"reactionType" varchar(20) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_adlib_comments" ADD CONSTRAINT "ai-madlib-generator-v2_adlib_comments_adlibId_ai-madlib-generator-v2_adlibs_id_fk" FOREIGN KEY ("adlibId") REFERENCES "public"."ai-madlib-generator-v2_adlibs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai-madlib-generator-v2_adlib_reactions" ADD CONSTRAINT "ai-madlib-generator-v2_adlib_reactions_adlibId_ai-madlib-generator-v2_adlibs_id_fk" FOREIGN KEY ("adlibId") REFERENCES "public"."ai-madlib-generator-v2_adlibs"("id") ON DELETE cascade ON UPDATE no action;